# –––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––
# # `deploy.yaml`
# client | Semantyk
#
# Created: Nov 29, 2023
# Modified: Nov 29, 2023
#
# Author(s): Semantyk Team
# Maintainer(s): Daniel Bakas <https://id.danielbakas.com>
#
# Copyright © Semantyk 2023. All rights reserved.
# –––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––

name: Deploy to Google App Engine

on:
  push:
    branches:
      - main
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout the Repository
      - uses: actions/checkout@v4
        name: Repository Checkout
      # 2. Setup Google Cloud SDK
      - uses: google-github-actions/setup-gcloud@v1
        name: Cloud SDK Configuration
      # 3. Authenticate with Google Cloud
      - uses: google-github-actions/auth@v2
        name: GCP Authentication
        with:
          credentials_json: ${{secrets.GCP_CREDENTIALS}}
      # 4. Deploy to Google App Engine
      # Deployment to 'main' service
      - if: github.ref == 'refs/heads/main'
        name: Deploy to Main Service
        run: gcloud app deploy app.yaml --project ${{secrets.GCP_PROJECT_ID}} --promote
      # Deployment to 'staging' service
      - if: github.ref == 'refs/heads/staging'
        name: Deploy to Staging Service
        run: gcloud app deploy app.yaml --project ${{secrets.GCP_PROJECT_ID}} --no-promote